version: 0.3.{build}
skip_tags: true
image:
  - Visual Studio 2017
  - ubuntu1804
init:
- ps:
environment:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  PowershellGalleryKey:
    secure: pRPJORXDzl7G6sU5Qz+K+tvDpzwYY+KgXDzAkY31Zb6cxKUJFFzYvzci7+Xgt0xN
  GitHubKey:
    secure: 64LLgggYJc3bb1D7G22KGYQFHknuWvoFZAUewRfX0QXV8gBjG97WwwU9lC2HNQ99
install:
- ps: |
    import-module powershellget
    Install-module PowerShellGet -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
    Remove-Module PowerShellGet -Force
    Import-Module PowerShellGet -Force

    Get-PackageProvider -Name NuGet -ForceBootstrap

    install-module pester -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
    install-module PSScriptAnalyzer -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
build_script:
- ps: |
      if($env:APPVEYOR_REPO_BRANCH -ne "master" -or $env:APPVEYOR_PULL_REQUEST_NUMBER -or $env:APPVEYOR_REPO_COMMIT_MESSAGE -like "skip: *" -or $env:OS -ne "Windows_NT") {
        .\Invoke-Build.ps1 build,test
      } else {
        .\Invoke-Build.ps1 publish
      }

artifacts:
  - path: AnsibleTower.zip

deploy:
- provider: GitHub
  tag: $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: 64LLgggYJc3bb1D7G22KGYQFHknuWvoFZAUewRfX0QXV8gBjG97WwwU9lC2HNQ99
  draft: true
  on:
    APPVEYOR_REPO_BRANCH: master
    OS: Windows_NT
